geoip2 /data/geoip/GeoLite2-Country.mmdb {
    auto_reload 1h;
    $geoip2_data_country_code country iso_code;
}

# Allowed countries by GeoIP
map $geoip2_data_country_code $is_allowed_country {
    default 0;
    AR 1;
}

# Allowed private networks
geo $remote_addr $is_private_ip {
    default 0;
    192.168.0.0/16 1;
    172.16.0.0/12 1;
    10.0.0.0/8 1;
}
