# Not allowed by default
set $allowed 0;

# Allow if the country is allowed
if ($is_allowed_country) {
    set $allowed 1;
}
# Allow if the request comes from a private network (internal call)
if ($is_private_ip) {
    set $allowed 1;
}

# Reject in any other case
if ($allowed = 0) {
    return 403;
}

