services:
  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=2000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - /mnt/p2p:/data
    restart: unless-stopped
    # ports:
    #   - "8989:8989"
    networks:
      - arr-suite
      - p2p

networks:
  arr-suite:
    external: true
  p2p:
    external: true