services:
  wg-easy:
    environment:
      # To generate the password hash, run this in your docker host (replace YOUR_PASSWORD with the password you want to set):
      #   docker run --rm -it ghcr.io/wg-easy/wg-easy:latest wgpw YOUR_PASSWORD
      # Then create an env var, and either surround the value with 'single quotes' or duplicate each $ (replace $ with $$)
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_HOST=${WG_HOST} # yourdomain.com without any http:// or https://

      # Optional:
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.0.50 # Put your AdGuard Home or PiHole IP here
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=25
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  etc_wireguard: