services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - vaultwarden
      - arr-suite
      - p2p

networks:
  vaultwarden:
    external: true
  arr-suite:
    external: true
  p2p:
    external: true